### ISSUE TITLE
Encoding issue with nonenglish search

### ISSUE THREAD

**Issue by shembelcut** [PedroHLC/ViewLyricsOpenSearcher#3]
there's an issue with encoding for noneglish characters 

![lyricserror2](https://cloud.githubusercontent.com/assets/1249548/5359393/e707735e-7ff7-11e4-8a5c-cfee351560b4.png)

![lyricserror](https://cloud.githubusercontent.com/assets/1249548/5359319/4102e790-7ff7-11e4-9981-ad47f69c49e7.png)

**Comment by PedroHLC** [comment]
Sorry for taking so long to solve it, I completely forgot about it, solved in 9887cc5395d51bc5f664d11930ae34cad6d681e9
