### ISSUE TITLE
noob

### ISSUE THREAD

**Issue by merichzte** [PedroHLC/ViewLyricsOpenSearcher#4]
Sorry for being a such a noob but, how do I compile this? in Eclipse?

**Comment by PedroHLC** [comment]
For start, Import project, open Tester in Eclipse editor, press play.
After that you can learn how to use this by analising the Tester.

**Comment by PedroHLC** [comment]
Read material:
[How to Import a Project](http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-importproject.htm)
[How to run a Tester class](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2FgettingStarted%2Fqs-12.htm)

The right way of using this project would be creating your own project and using this one as a Library for it, you can easily do this in Eclipse putting ViewLyricsOpenSearcher as a dependency for your project.
[See 'Projects Tab'](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fref-properties-build-path.htm)

An even more right way to do would be:
[Creating a JAR file](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftasks-33.htm)
[And import it in your final project](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fbuildpath%2Fref-preferences-user-libraries.htm)

**Comment by merichzte** [comment]
Thanks for the response. Eventually I would like to incorporate this code. I imported and tried to run the tester, but I get: 
>[Fatal Error] :1:1: Content is not allowed in prolog.
>org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
>	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.pedrohlc.viewlyricsppensearcher.ViewLyricsSearcher.parseResultXML(ViewLyricsSearcher.java:212)
	at com.pedrohlc.viewlyricsppensearcher.ViewLyricsSearcher.searchQuery(ViewLyricsSearcher.java:103)
	at com.pedrohlc.viewlyricsppensearcher.ViewLyricsSearcher.search(ViewLyricsSearcher.java:66)
	at com.pedrohlc.viewlyricsppensearcher.Tester.main(Tester.java:21)*

I have JRE 8. Eclipse Maven on Windows XP. Some forums say this is a UTF-BOM issue, but before delving into code and adding a function to skip BOM (which would take me some time), I wonder why it works for you, but not me.

**Comment by PedroHLC** [comment]
Might be 1: Different search parameters, 2: I use OpenJDK, 3: The last time I build this project I was using JRE 7.
Anyway this should be working well for anyone, as this is a different issue, please create another issue. And, for debugging purpose only, put a ```System.out.println(neomagic.toString();)``` before ViewLyricsSearcher.java:170 and include it on issue description, so we can see the raw decrypted XML.
I believe this have something to do with issue #3 that I don't remember solving for reasons I don't remember either....

**Comment by merichzte** [comment]
Yes thanks for help on the compile issue
